language: cpp

compiler:
- clang
- gcc

os:
- linux
- osx

before_install: make make_dirs && make clean_obj

install: make

# Execute all the binary files in the bin/ directory
script: find bin/ -maxdepth 1 -type f -exec {} \;

notifications:
    email: false
